version: '3'

services:
  product-service:
    image: golang:latest
    container_name: product-service
    build: product-service
    restart: always
    ports:
      - 50051:50051
    environment:
      PORT: 50051

  user-service:
    image: golang:latest
    container_name: user-service
    build: user-service
    restart: always
    ports:
      - 50052:50052
    environment:
      DB_HOST: mysql-db
      DB_USER: fchrgrib
      DB_PASSWORD: fchrgrib2310
      DB_NAME: user-db
      DB_PORT: 3306
      PORT: 50052
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: fchrgrib2310
      MYSQL_DATABASE: user-db
      MYSQL_USER: fchrgrib
      MYSQL_PASSWORD: fchrgrib2310